### ISSUE TITLE
pysftp.CnOpts() gives No Host Keys Found

### ISSUE THREAD

**Issue by hududed** [Clean-Cole/pysftp#3]
Hello

I use the latest pysftp 0.2.9.

I run the following code:
```
import pysftp
cnopts = pysftp.CnOpts()
cnopts.hostkeys = None
``` 
And receive the following error:
```
---------------------------------------------------------------------------
HostKeysException                         Traceback (most recent call last)
<ipython-input-10-7c5a03189319> in <module>
      1 import pysftp
----> 2 pysftp.CnOpts()

~\Anaconda3\envs\controller2\lib\site-packages\pysftp-0.2.9-py3.7.egg\pysftp\__init__.py in __init__(self, knownhosts)
     62         else:
     63             if len(self.hostkeys.items()) == 0:
---> 64                 raise HostKeysException('No Host Keys Found')
     65 
     66     def get_hostkey(self, host):

HostKeysException: No Host Keys Found
```

Ultimately I want it to read from `~/.ssh/known_hosts` or just leave bypass the host keys but I get the error even before I am able to set it as such.

Please advise

**Comment by hukm** [comment]
Hello

I have met the similar problem today. It seems that your `~/.ssh/known_hosts` is empty. To overcome the issue I have created fake known_hosts file with one row of some host and added this file to a parameter at the cnopts initialization as so:

`cnopts = pysftp.CnOpts(knownhosts=os.path.expanduser(os.path.join('~', '.ssh', 'fake_known_hosts')))
  cnopts.hostkeys = None`

**Comment by Clean-Cole** [comment]
Im flattered that people are finding this repo. It's very old work from a long time ago.  I'm happy to merge any fixes or improvements if you haven't already just forked, but there might be some more mature packages out that to help you faster.
