### ISSUE TITLE
ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by sixtone** [Clean-Cole/pysftp#4]
Hello!

Not sure if this is a pysftp bug but as of late I am getting an error message that states:

`Exception ignored in: <function Connection.__del__ at 0x000001A9EF6CD288> Traceback (most recent call last): File "C:\Users\21321\AppData\Roaming\Python\Python37\site-packages\pysftp\__init__.py", line 1013, in __del__ File "C:\Users\21321\AppData\Roaming\Python\Python37\site-packages\pysftp\__init__.py", line 795, in close ImportError: sys.meta_path is None, Python is likely shutting down`

Whenever the connection is beeing closed. It's pointing to "import logging" in the init.py file. Thought i'd put this error here, just in case, it's not somehow my system causing the error in the first place :)

Best Regards

**Comment by omiid-ad** [comment]
> Hello!
> 
> Not sure if this is a pysftp bug but as of late I am getting an error message that states:
> 
> `Exception ignored in: <function Connection.__del__ at 0x000001A9EF6CD288> Traceback (most recent call last): File "C:\Users\21321\AppData\Roaming\Python\Python37\site-packages\pysftp\__init__.py", line 1013, in __del__ File "C:\Users\21321\AppData\Roaming\Python\Python37\site-packages\pysftp\__init__.py", line 795, in close ImportError: sys.meta_path is None, Python is likely shutting down`
> 
> Whenever the connection is beeing closed. It's pointing to "import logging" in the init.py file. Thought i'd put this error here, just in case, it's not somehow my system causing the error in the first place :)
> 
> Best Regards

Same here!

**Comment by abubelinha** [comment]
Same problem here.
Windows 7 
Python 3.8 
pysftp 0.2.9

**Comment by Clean-Cole** [comment]
Im flattered that people are finding this repo. It's very old work that I think was built in Python2.7. I'm happy to merge any fixes or improvements if you haven't already just forked, but there might be some more mature packages out that to help you faster.

I recommend using the Paramiko package directly for sftp usage in Python

https://docs.paramiko.org/en/stable/api/sftp.html

**Comment by abubelinha** [comment]
Thanks for the info :+1: 
I wonder why a comment like yours does not appear in the [original pysftp site](https://bitbucket.org/dundeemt/pysftp/src/master/)
(looks like an orphan project, but I don't know how to open bitbucket issues @dundeemt)
